"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { Database, Lock, Mail, Shield, Sparkles } from "lucide-react";
import { DotsBackground } from "@/components/ui/AnimatedBackground";
import GlassCard from "@/components/ui/GlassCard";
import Button from "@/components/ui/Button";
import NovaFooterLinks from "@/components/nova/NovaFooterLinks";

const sections = [
  { title: "1. Information We Process", body: <><p>Nova does not require your name or email address to use the app.</p><p>When you choose to use Nova&apos;s AI features, the app may process portrait photos and other images selected by you, reference images used for virtual try-ons, text instructions, AI-generated images and hairstyle recommendations, a random technical user identifier, subscription status and generation-credit usage, and technical request or error information.</p><p>Nova does not use facial images to identify or authenticate you and does not create a biometric identification profile.</p></> },
  { title: "2. Photos and AI Image Processing", body: <><p>When you request a hairstyle analysis, virtual try-on, or image generation, the photos and instructions needed to provide that feature are securely transmitted through Nova&apos;s server infrastructure hosted by Supabase and processed using OpenAI&apos;s API.</p><p>Your images are used only to provide the feature you requested. Nova does not sell your photos or use them for advertising.</p><p>Nova currently uses OpenAI&apos;s <code>/v1/chat/completions</code> endpoint to analyze images and <code>/v1/images/edits</code> to generate edited images. Data submitted to these endpoints is not used to train OpenAI&apos;s models unless the API account owner explicitly opts in. These endpoints have no application-state retention for Nova&apos;s requests. OpenAI may retain abuse-monitoring logs, which can include submitted images, prompts, and generated outputs, for up to 30 days by default, or longer when required by law or reasonably necessary for safety.</p><p>Image inputs are automatically scanned for child sexual abuse material. If an image is flagged, OpenAI may retain it for manual review, including when reduced-retention controls are enabled.</p><p>Nova does not intentionally save the original uploaded photo in its own server database, but cannot state that every copy is deleted immediately because OpenAI may retain limited safety logs as described above. See <a href="https://developers.openai.com/api/docs/guides/your-data" target="_blank" rel="noopener noreferrer">OpenAI&apos;s data controls documentation</a>.</p><p>You should only upload photos that you own or have permission to use. Do not upload another person&apos;s image without their consent.</p></> },
  { title: "3. Data Stored on Your Device", body: <><p>Saved results, Studio history, profile information, and progress data may be stored locally on your device. This information generally remains there until you delete it, clear the app&apos;s data, or uninstall the app.</p><p>Apple may include locally stored app data in device or iCloud backups according to your Apple settings.</p></> },
  { title: "4. Payments and Subscriptions", body: <><p>Nova offers optional in-app purchases and subscriptions processed securely through Apple&apos;s App Store. We do not collect or store your complete payment-card information.</p><p>Nova uses RevenueCat to verify subscription status and provide access to paid features. RevenueCat may process a random app user identifier, purchased product, subscription status, and transaction information.</p><p>Deleting Nova or requesting deletion of your Nova data does not automatically cancel an Apple subscription. You can manage or cancel your subscription through your Apple account settings.</p></> },
  { title: "5. Third-Party Services", body: <><p>Nova uses OpenAI for AI photo analysis and image generation, Supabase for anonymous authentication, secure server functions, and technical usage records, RevenueCat for subscription management, and Apple for distribution, purchases, subscriptions, and device services.</p><p>These services receive only the information reasonably necessary to provide their function. Nova does not use third-party advertising or cross-app tracking tools.</p></> },
  { title: "6. Data Sharing and Retention", body: <><p>We do not sell or rent your personal data. Information is shared only with the service providers listed above when necessary to provide Nova&apos;s features, process subscriptions, maintain security, comply with the law, or protect our rights.</p><p>Photos and text submitted for AI processing are not intentionally stored in Nova&apos;s own server database after the requested operation. OpenAI may retain abuse-monitoring logs containing submitted content for up to 30 days by default, subject to legal and safety exceptions. Images flagged by OpenAI&apos;s child-safety classifier may be retained for manual review.</p><p>Technical account, subscription, request, and generation records may be retained for as long as reasonably necessary to operate the service, prevent fraud, comply with legal obligations, and resolve disputes.</p></> },
  { title: "7. Your Choices and Data Deletion", body: <><p>You can remove Nova&apos;s access to your camera or photo library at any time through iOS Settings. Photo-based features may no longer work if permission is removed.</p><p>To request access to or deletion of your Nova server data, email <a href="mailto:hypernovationtech@gmail.com">hypernovationtech@gmail.com</a> with the subject <strong>Nova Data Request</strong>. We may ask for limited technical information needed to locate the anonymous account and verify the request.</p></> },
  { title: "8. Children’s Privacy", body: <p>Nova is not intended for children under 13. We do not knowingly collect personal information from children under 13. If you believe a child has provided information without appropriate authorization, please contact us.</p> },
  { title: "9. AI Results", body: <p>Nova&apos;s images and recommendations are generated using artificial intelligence. Results may be inaccurate, unexpected, or different from what can be achieved in real life. Nova does not provide medical advice, medical diagnosis, or professional health advice.</p> },
  { title: "10. Changes to This Policy", body: <p>We may update this Privacy Policy if Nova&apos;s features, service providers, or legal requirements change. Changes will be posted on this page with an updated date.</p> },
  { title: "11. Contact", body: <p>For questions about this Privacy Policy or your data, contact <a href="mailto:hypernovationtech@gmail.com">hypernovationtech@gmail.com</a>.</p> },
];

export default function NovaPrivacyPolicyPage() {
  return <div className="nova-light relative min-h-screen px-4 pb-20 pt-32"><DotsBackground className="nova-dots" /><div className="relative z-10 mx-auto max-w-5xl">
    <motion.header initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-14 text-center"><div className="mb-6 inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-6 py-3"><Shield className="h-5 w-5 text-[#FA93FA]" /><span className="font-medium text-[#FA93FA]">Nova Privacy Policy</span></div><h1 className="text-gradient text-4xl font-bold md:text-6xl">Privacy Policy</h1><p className="mt-5 text-gray-400">Last updated: August 2026</p></motion.header>
    <GlassCard hover={false} className="mb-8"><p className="text-lg leading-relaxed text-gray-300">Nova (&quot;we&quot;, &quot;our&quot;, or &quot;the app&quot;) respects your privacy. This Privacy Policy explains how your information is handled when you use the Nova application.</p></GlassCard>
    <div className="space-y-6">{sections.map((section) => <GlassCard key={section.title} hover={false}><h2 className="mb-4 text-xl font-bold text-white">{section.title}</h2><div className="space-y-4 leading-relaxed text-gray-300 [&_a]:text-[#FA93FA] [&_a]:underline [&_code]:rounded [&_code]:bg-white/10 [&_code]:px-1.5 [&_code]:py-0.5">{section.body}</div></GlassCard>)}</div>
    <section className="py-16"><h2 className="mb-8 text-center text-3xl font-bold">Your Privacy Matters</h2><div className="grid gap-6 md:grid-cols-3">{[[Database,"Your Photos, Your Choice","Photos are processed only when you request an AI feature."],[Lock,"Secure AI Processing","Images are securely transmitted to provide your analysis or generation."],[Sparkles,"No Advertising Tracking","No targeted advertising or cross-app tracking."]].map(([Icon,title,text]) => { const CardIcon = Icon as typeof Database; return <GlassCard key={title as string} className="text-center"><CardIcon className="mx-auto mb-4 h-8 w-8 text-[#FA93FA]"/><h3 className="mb-2 font-bold">{title as string}</h3><p className="text-sm text-gray-400">{text as string}</p></GlassCard>; })}</div></section>
    <div className="flex flex-col justify-center gap-4 sm:flex-row"><Button href="/projects/nova/support" variant="outline">Back to Support</Button><Link href="mailto:hypernovationtech@gmail.com"><Button>Contact Us <Mail className="h-5 w-5" /></Button></Link></div><NovaFooterLinks />
  </div></div>;
}
