import LegalPage, { LegalSection } from "@/components/fluent/LegalPage";

const toc = [
  ["introduction", "Introduction"], ["local-data", "Information stored locally"], ["apple-revenuecat", "Apple and RevenueCat"], ["purposes", "Purposes of processing"], ["legal-bases", "Legal bases"], ["retention", "Data retention"], ["transfers", "International transfers"], ["security", "Data security"], ["children", "Children’s privacy"], ["rights", "Privacy rights"], ["gdpr", "European privacy rights"], ["us-rights", "US state privacy rights"], ["requests", "Privacy requests"], ["third-parties", "Third-party services"], ["future-features", "Future features"], ["changes", "Changes and contact"],
].map(([id, label]) => ({ id, label }));

export default function PrivacyPage() {
  return <LegalPage eyebrow="Fluent AI · Legal" title="Privacy Policy" effective="August 20, 2026" updated="August 20, 2026" introduction="This Privacy Policy explains how Fluent AI handles information when you use Fluent, our iOS language-learning application." toc={toc}>
    <LegalSection id="introduction" title="1. Introduction"><p>Fluent AI is the public service and brand name used for Fluent. The application currently does not require you to create a personal account.</p><p>This policy describes the current version of Fluent and does not claim that no information is processed: Apple and RevenueCat process information needed for purchases, subscriptions, and entitlements.</p><p>Fluent AI does not sell personal information.</p></LegalSection>
    <LegalSection id="local-data" title="2. Information stored locally"><p>Most learning information is stored locally on your device using Apple storage technologies such as UserDefaults. This may include your interface language, selected learning languages, learning objective, onboarding status, cards studied, answers, mastery status, XP, session count and duration, daily activity, streaks, and progress statistics.</p><p>Local learning data may be deleted when you uninstall Fluent or erase its data. It may not transfer to another device because Fluent does not currently provide cloud synchronization.</p><p>Fluent does not currently record, upload, or store your voice. Pronunciation playback uses Apple’s native on-device text-to-speech functionality; it speaks content to you rather than recording your speech.</p></LegalSection>
    <LegalSection id="apple-revenuecat" title="3. Information processed by Apple and RevenueCat"><p>Apple distributes Fluent and processes in-app purchases, subscription billing, payments, and purchase restoration. Fluent AI does not directly receive or store your complete payment-card information.</p><p>RevenueCat manages Premium subscription status, products and offers, purchase restoration, and user entitlements. It may process an anonymous application user identifier, subscription status, purchased product identifiers, transaction and expiration dates, store country or region, and technical information required to operate these functions.</p></LegalSection>
    <LegalSection id="purposes" title="4. Purposes for processing information"><ul><li>Store your preferences, lessons, progress, XP, mastery, activity, and streaks on your device.</li><li>Provide vocabulary, verb, sentence, expression, flashcard, conversation-scenario, course, and pronunciation-playback features.</li><li>Offer and restore Premium access.</li><li>Process subscription status and entitlements.</li><li>Respond to support and privacy requests.</li><li>Protect the service and comply with applicable legal obligations.</li></ul></LegalSection>
    <LegalSection id="legal-bases" title="5. Legal bases where applicable"><p>Where the GDPR or similar law applies, processing may rely on performance of a contract to provide Fluent and Premium features; legitimate interests in operating, securing, and supporting the service; consent where legally required; and compliance with legal obligations.</p><p>Local settings you choose are processed to provide the features you request. You can erase local data by deleting the application or its data, subject to Apple device and backup settings.</p></LegalSection>
    <LegalSection id="retention" title="6. Data retention"><p>Local learning data remains on your device until you erase it, erase the application’s data, or uninstall Fluent, subject to any device backups managed through your Apple settings.</p><p>Apple and RevenueCat retain purchase, subscription, entitlement, and technical information according to their respective policies and legal obligations. Fluent AI does not set or control those providers’ independent retention periods.</p><p>Support emails are retained only as reasonably necessary to respond, maintain support records, protect legal rights, and meet legal obligations. No fixed period is stated because one has not been legally verified.</p></LegalSection>
    <LegalSection id="transfers" title="7. International data transfers"><p>Apple and RevenueCat may process information in countries outside your place of residence. Their privacy policies describe their processing locations and transfer safeguards. Where applicable, international transfers must use a legally recognized mechanism.</p></LegalSection>
    <LegalSection id="security" title="8. Data security"><p>Fluent limits current remote processing to services needed for App Store distribution, purchases, subscriptions, restoration, and entitlements. Local learning data benefits from the safeguards provided by iOS and your device security settings.</p><p>No storage or transmission method can be guaranteed completely secure. Keep your device and Apple Account protected and avoid sharing unnecessary sensitive information in support requests.</p></LegalSection>
    <LegalSection id="children" title="9. Children’s privacy"><p>Fluent is not intended for children who cannot lawfully use the service independently in their location. A parent or legal guardian should authorize use where required. If you believe a child has provided information improperly, contact us so the issue can be reviewed.</p></LegalSection>
    <LegalSection id="rights" title="10. User privacy rights"><p>Depending on your location, you may have rights concerning personal information processed about you. You can control local learning data through the application, device settings, and deletion of the application. Purchase and subscription information may also be managed through your Apple Account.</p></LegalSection>
    <LegalSection id="gdpr" title="11. European privacy rights under the GDPR"><p>Where applicable, European users may request access, correction, deletion, restriction, objection, and portability of personal information, and may withdraw consent where processing relies on consent. You may also file a complaint with the relevant data-protection supervisory authority.</p><p>These rights may be subject to legal limitations and verification requirements.</p></LegalSection>
    <LegalSection id="us-rights" title="12. General US state privacy rights"><p>Depending on your US state of residence and the law applicable to Fluent AI, you may have rights to request information about personal data, access it, correct it, delete it, or receive a portable copy, and to appeal certain decisions. Fluent AI does not claim compliance with a particular state statute where applicability has not been legally verified.</p><p>Fluent AI does not sell personal information.</p></LegalSection>
    <LegalSection id="requests" title="13. How to request access, correction, or deletion"><p>Email <a href="mailto:hypernovationtech@gmail.com?subject=Fluent%20AI%20Privacy%20Request">hypernovationtech@gmail.com</a> with the subject “Fluent AI Privacy Request” and describe whether you request access, correction, or deletion.</p><p>We may request limited information needed to verify your request and identify relevant RevenueCat or support records. Because Fluent does not currently require a personal account and most learning data stays on your device, Fluent AI may not possess a copy of that local data.</p><p>Deleting Fluent does not cancel an Apple subscription. Manage subscriptions separately in your Apple Account settings.</p></LegalSection>
    <LegalSection id="third-parties" title="14. Third-party services"><p><a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener noreferrer">Apple Privacy Policy</a> — App distribution, payments, subscriptions, purchase restoration, and native on-device text-to-speech.</p><p><a href="https://www.revenuecat.com/privacy/" target="_blank" rel="noopener noreferrer">RevenueCat Privacy Policy</a> — Premium subscription status, products and offers, purchase restoration, and entitlements.</p></LegalSection>
    <LegalSection id="future-features" title="15. Future features"><p>This Privacy Policy will be updated before Fluent introduces features involving voice recording or speech recognition, cloud synchronization, personal accounts, artificial-intelligence conversations, analytics or advertising tools, or remote storage of learning data.</p></LegalSection>
    <LegalSection id="changes" title="16. Changes and contact"><p>We may update this Privacy Policy when Fluent changes or legal requirements evolve. The effective and last-updated dates will be revised when changes are posted.</p><p>Service: Fluent AI · Application: Fluent · Bundle ID: com.biohack.Fluent</p><p>Privacy and support requests: <a href="mailto:hypernovationtech@gmail.com">hypernovationtech@gmail.com</a>.</p></LegalSection>
  </LegalPage>;
}
