"use client";

import { motion } from "framer-motion";
import { CheckCircle2, Mail, ShieldCheck } from "lucide-react";
import { DotsBackground } from "@/components/ui/AnimatedBackground";
import GlassCard from "@/components/ui/GlassCard";
import Button from "@/components/ui/Button";
import NovaFooterLinks from "@/components/nova/NovaFooterLinks";

const steps = ["Email us from an address where we can reply.", "Use the subject “Nova Data Request” and state whether you want access or deletion.", "We may request limited technical information to locate the anonymous account connected to your installation.", "We will confirm the outcome after verification, subject to any legally required retention."];

export default function NovaDataRequestPage() { return <div className="relative min-h-screen px-4 pb-20 pt-32"><DotsBackground/><div className="relative z-10 mx-auto max-w-4xl"><motion.header initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mb-14 text-center"><ShieldCheck className="mx-auto mb-5 h-12 w-12 text-[#FA93FA]"/><h1 className="text-gradient text-4xl font-bold md:text-6xl">Manage your Nova data</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-gray-400">You can request access to or deletion of the server data associated with your anonymous Nova session.</p></motion.header><GlassCard hover={false}><h2 className="mb-7 text-2xl font-bold">How to make a request</h2><ol className="space-y-5">{steps.map((step,index)=><li key={step} className="flex gap-4 text-gray-300"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#FA93FA]/15 text-sm font-bold text-[#FA93FA]">{index+1}</span><span className="pt-0.5 leading-relaxed">{step}</span></li>)}</ol><div className="mt-9"><Button href="mailto:hypernovationtech@gmail.com?subject=Nova%20Data%20Request"><Mail className="h-5 w-5"/>Start a data request</Button></div></GlassCard><div className="mt-8 grid gap-6 md:grid-cols-2"><GlassCard hover={false}><CheckCircle2 className="mb-4 h-7 w-7 text-[#FA93FA]"/><h2 className="mb-3 text-xl font-bold">On-device data</h2><p className="leading-relaxed text-gray-400">Saved results, history, profile, and progress may remain on your iPhone until you delete them, clear the app’s data, or uninstall Nova.</p></GlassCard><GlassCard hover={false}><CheckCircle2 className="mb-4 h-7 w-7 text-[#FA93FA]"/><h2 className="mb-3 text-xl font-bold">Apple subscriptions</h2><p className="leading-relaxed text-gray-400">A data-deletion request does not cancel your subscription. Manage it separately in your Apple account settings.</p></GlassCard></div><NovaFooterLinks /></div></div> }
