import LegalPage, { LegalSection } from "@/components/fluent/LegalPage";

export default function TermsPage() {
  return (
    <LegalPage eyebrow="Fluent AI · Legal" title="Terms of Service" updated="August 20, 2026" introduction="These Terms of Service govern your access to and use of Fluent AI. By downloading or using the app, you agree to these terms. If you do not agree, do not use Fluent AI.">
      <LegalSection title="1. Service operator"><p>Fluent AI is operated by <strong>[LEGAL NAME TO BE ADDED BEFORE PUBLICATION]</strong>. Contact: <a href="mailto:hypernovationtech@gmail.com">hypernovationtech@gmail.com</a>. No company name or postal address has been inserted because that information was not provided.</p></LegalSection>
      <LegalSection title="2. Eligibility and accounts"><p>You must meet the minimum age required to accept these terms in your location. If you cannot legally accept them yourself, a parent or legal guardian must do so for you.</p><p>If Fluent AI offers accounts, you are responsible for accurate information, protecting your credentials, and activity under your account. Notify support if you believe access has been compromised.</p></LegalSection>
      <LegalSection title="3. License and acceptable use"><p>You receive a personal, limited, non-exclusive, non-transferable, and revocable license to use Fluent AI for lawful language learning on devices you own or control, subject to Apple’s applicable rules.</p><p>You may not misuse the service, interfere with its operation, bypass access controls, reverse engineer it except where law expressly permits, impersonate another person, infringe intellectual-property or privacy rights, submit content you have no right to use, or use Fluent AI for illegal, harmful, fraudulent, exploitative, harassing, hateful, or abusive activity.</p></LegalSection>
      <LegalSection title="4. Your content"><p>You retain your rights in content you submit. You grant the limited permission needed to process your spoken or written input and provide conversations, transcriptions, corrections, and feedback. You are responsible for your content and for having the necessary rights to submit it.</p></LegalSection>
      <LegalSection title="5. AI-generated content"><p>Fluent AI uses artificial intelligence. Replies, translations, transcriptions, corrections, explanations, and other outputs may be incomplete, inaccurate, inappropriate, or unexpected. Do not rely on them as professional, legal, medical, financial, or safety advice. Use your judgment and verify important information independently.</p></LegalSection>
      <LegalSection title="6. Subscriptions, trials, and billing"><p>Fluent AI may offer subscriptions or free trials through Apple’s App Store. The price, subscription period, trial length, and included features shown in the app before purchase control your offer. Payment is charged to your Apple Account according to Apple’s terms.</p><p>Unless you cancel within the time Apple specifies, a free trial may convert to a paid subscription and a subscription may renew automatically. Manage or cancel subscriptions in your Apple Account settings. Deleting Fluent AI or an account does not cancel an Apple subscription. Refund requests are governed by Apple’s policies and applicable law.</p></LegalSection>
      <LegalSection title="7. Intellectual property"><p>Fluent AI, including its software, interface, branding, and original materials, is protected by intellectual-property laws. Except for the limited license above, no rights in Fluent AI are transferred to you. Third-party materials remain the property of their respective owners.</p></LegalSection>
      <LegalSection title="8. Service availability and changes"><p>Features may change, and the service may be interrupted for maintenance, security, technical issues, provider changes, or circumstances beyond reasonable control. Continuous, error-free, or permanent availability is not guaranteed.</p></LegalSection>
      <LegalSection title="9. Suspension and termination"><p>Access may be restricted or terminated if you materially violate these terms, misuse the service, create risk or harm, or if action is reasonably necessary for security or legal compliance. You may stop using Fluent AI at any time. Apple subscriptions must be canceled separately.</p></LegalSection>
      <LegalSection title="10. Disclaimers"><p>To the fullest extent permitted by law, Fluent AI is provided “as is” and “as available,” without warranties of accuracy, uninterrupted availability, fitness for a particular purpose, or a particular learning outcome. Nothing here limits non-waivable consumer rights.</p></LegalSection>
      <LegalSection title="11. Limitation of liability"><p>To the fullest extent permitted by law, the service operator will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of Fluent AI or reliance on AI output. This does not exclude liability that cannot legally be excluded.</p></LegalSection>
      <LegalSection title="12. Governing terms"><p>Governing law, jurisdiction, and the operator’s complete legal identity must be completed before publication: <strong>[GOVERNING LAW AND JURISDICTION TO BE ADDED]</strong>. Mandatory rights available to consumers in their country of residence remain unaffected.</p></LegalSection>
      <LegalSection title="13. Changes and contact"><p>These terms may be updated to reflect changes to Fluent AI or legal requirements. Material changes will be communicated where required. Questions: <a href="mailto:hypernovationtech@gmail.com">hypernovationtech@gmail.com</a>.</p></LegalSection>
    </LegalPage>
  );
}
