import LegalPage, { LegalSection } from "@/components/fluent/LegalPage";

const toc = [
  ["introduction", "Introduction and acceptance"], ["eligibility", "Eligibility"], ["license", "Limited license"], ["permitted-use", "Permitted use"], ["prohibited", "Prohibited activities"], ["ip", "Intellectual property"], ["education", "Educational content"], ["no-guarantee", "No proficiency guarantee"], ["premium", "Premium subscriptions"], ["trials", "Free trials"], ["renewal", "Renewal and prices"], ["cancellation", "Cancellation and refunds"], ["restoration", "Purchase restoration"], ["availability", "Availability and updates"], ["termination", "Suspension and termination"], ["disclaimers", "Disclaimers"], ["liability", "Limitation of liability"], ["governing", "Governing terms"], ["changes", "Changes"], ["contact", "Contact"],
].map(([id, label]) => ({ id, label }));

export default function TermsPage() {
  return <LegalPage eyebrow="Fluent AI · Legal" title="Terms of Service" effective="August 20, 2026" updated="August 20, 2026" introduction="These Terms of Service govern your use of Fluent, the iOS language-learning application offered under the Fluent AI service and brand name." toc={toc}>
    <LegalSection id="introduction" title="1. Introduction and acceptance"><p>By downloading, accessing, or using Fluent, you agree to these Terms of Service. If you do not agree, do not use the application. Apple’s applicable App Store terms also apply.</p></LegalSection>
    <LegalSection id="eligibility" title="2. Eligibility and age requirements"><p>You must be legally able to accept these terms in your location. If you are below the age at which you may accept them independently, a parent or legal guardian must review and accept them for you.</p><p>Fluent does not currently require a personal account.</p></LegalSection>
    <LegalSection id="license" title="3. Personal and limited license"><p>Fluent AI grants you a personal, limited, non-exclusive, non-transferable, non-sublicensable, and revocable license to use Fluent on Apple devices you own or control for personal language learning, subject to these terms and Apple’s rules.</p></LegalSection>
    <LegalSection id="permitted-use" title="4. Permitted use"><p>You may use Fluent’s vocabulary, verbs, sentences, natural expressions, flashcards, scenarios, pronunciation playback, courses, levels, XP, mastery, statistics, daily activity, and streak features for lawful personal educational purposes.</p></LegalSection>
    <LegalSection id="prohibited" title="5. Prohibited activities"><p>You may not use Fluent unlawfully; interfere with security or operation; bypass subscriptions or access controls; copy, distribute, resell, scrape, or commercially exploit the application or its content; reverse engineer it except where law expressly permits; introduce malicious code; impersonate others; or infringe intellectual-property, privacy, or other rights.</p></LegalSection>
    <LegalSection id="ip" title="6. Intellectual property"><p>Fluent, its software, design, branding, exercises, course structure, and original materials are protected by intellectual-property laws. Except for the limited license above, these terms do not transfer any ownership rights to you. Third-party content remains the property of its respective owners.</p></LegalSection>
    <LegalSection id="education" title="7. Educational content"><p>Fluent is an educational aid. Language examples, translations, pronunciation playback, exercises, and explanations may contain errors, vary by region, or omit context. Verify important language use with a qualified teacher or authoritative source.</p><p>“Beginner,” “Intermediate,” and “Advanced” describe Fluent’s internal learning paths unless the application expressly associates a path with an official Common European Framework of Reference for Languages (CEFR) level.</p></LegalSection>
    <LegalSection id="no-guarantee" title="8. No guarantee of language proficiency"><p>Fluent AI does not guarantee fluency, employment, examination results, admission, a diploma, certification, or any particular educational outcome. Progress depends on factors including your practice, prior knowledge, and individual circumstances.</p></LegalSection>
    <LegalSection id="premium" title="9. Premium subscriptions"><p>Fluent may offer monthly and yearly Premium subscriptions. Payments and subscriptions are processed by Apple. Fluent AI does not directly receive or store your complete payment-card information.</p><p>The exact features, prices, billing periods, and offers displayed in Fluent and the App Store before purchase take priority over general descriptions on this website.</p></LegalSection>
    <LegalSection id="trials" title="10. Free trials"><p>When displayed in Fluent or the App Store, a subscription may include a free trial. The displayed trial duration and eligibility conditions control. A free trial may convert into a paid subscription unless you cancel before the trial ends according to Apple’s displayed terms.</p></LegalSection>
    <LegalSection id="renewal" title="11. Automatic renewal, prices, and price changes"><p>Subscriptions renew automatically unless cancelled according to Apple’s displayed terms. Apple charges your Apple Account. The exact current price, currency, billing period, and renewal details shown in Fluent and the App Store at purchase take priority.</p><p>Prices may change. Apple will provide any notice or consent process required by its policies or applicable law.</p></LegalSection>
    <LegalSection id="cancellation" title="12. Subscription cancellation and refunds"><p>You can manage or cancel your subscription through your Apple Account settings. Deleting Fluent does not automatically cancel a subscription. Cancellation generally takes effect at the end of the paid period unless Apple or applicable law provides otherwise.</p><p>Refund requests are handled according to Apple’s policies and applicable law. Fluent AI cannot directly issue an App Store refund where Apple controls the transaction.</p></LegalSection>
    <LegalSection id="restoration" title="13. Purchase restoration"><p>Use the purchase-restoration option in Fluent with the Apple Account used for the original purchase. RevenueCat may process the technical purchase and entitlement information needed to restore access.</p></LegalSection>
    <LegalSection id="availability" title="14. Service availability and application updates"><p>Fluent AI may update, improve, replace, suspend, or discontinue parts of Fluent. Features may be unavailable because of maintenance, device compatibility, App Store services, technical issues, or circumstances outside reasonable control.</p><p>You may need to install application or iOS updates to continue using certain features. Continuous, permanent, or error-free availability is not guaranteed.</p></LegalSection>
    <LegalSection id="termination" title="15. Suspension or termination"><p>Fluent AI may restrict or terminate access when reasonably necessary to address a material violation of these terms, fraud, circumvention of Premium access, security threats, legal requirements, or harm to the service or others. You may stop using Fluent at any time. Apple subscriptions must be cancelled separately.</p></LegalSection>
    <LegalSection id="disclaimers" title="16. Disclaimer of warranties"><p>To the fullest extent permitted by law, Fluent is provided “as is” and “as available,” without warranties of uninterrupted operation, accuracy, merchantability, fitness for a particular purpose, or a particular learning result. Nothing in these terms limits mandatory consumer rights that cannot be waived.</p></LegalSection>
    <LegalSection id="liability" title="17. Limitation of liability"><p>To the fullest extent permitted by law, Fluent AI will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, loss of data, loss of opportunity, or reliance on educational content arising from use of Fluent. This limitation does not apply where liability cannot legally be excluded or limited.</p></LegalSection>
    <LegalSection id="governing" title="18. Governing terms"><p><strong>[GOVERNING LAW AND JURISDICTION TO BE COMPLETED BEFORE PUBLICATION IF LEGALLY REQUIRED]</strong></p><p>Mandatory consumer protections available in your country or region remain unaffected. If any provision is unenforceable, the remaining provisions continue to apply to the extent permitted by law.</p></LegalSection>
    <LegalSection id="changes" title="19. Changes to the Terms"><p>Fluent AI may update these terms to reflect changes to Fluent, Apple or RevenueCat services, or legal requirements. The effective and last-updated dates will be revised. Where required, additional notice will be provided before material changes take effect.</p></LegalSection>
    <LegalSection id="contact" title="20. Contact information"><p>Service: Fluent AI · Application: Fluent · Bundle ID: com.biohack.Fluent</p><p>Website: <a href="https://hypernova-5xy8.vercel.app/fluent-ai">https://hypernova-5xy8.vercel.app/fluent-ai</a></p><p>Support: <a href="mailto:hypernovationtech@gmail.com">hypernovationtech@gmail.com</a></p></LegalSection>
  </LegalPage>;
}
